"""create sensors and readings

Revision ID: 5e40baad7ba2
Revises: 7a90d76fe0cf
Create Date: 2025-12-03 20:07:22.198310

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e40baad7ba2'
down_revision = '7a90d76fe0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
