"""init

Revision ID: 7a90d76fe0cf
Revises: 
Create Date: 2025-12-03 19:58:18.514950

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a90d76fe0cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('current_a', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('power_w', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('sensors')
    # ### end Alembic commands ###
